#!/bin/bash
# dnanexus_bigwig_coverage_map_report 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

# Exit at any point if there is any error and output each line as it is executed (for debugging)
set -e -x -o pipefail

echo "${input_bam}"

main() {
    # SET VARIABLES
    # Store the API key. Grants the script access to DNAnexus resources
    API_KEY=$(dx cat project-FQqXfYQ0Z0gqx7XG9Z2b4K43:mokaguys_nexus_auth_key)

    # Set the output directory
    mkdir -p "${output_directory}"
    cd "${output_directory}"

    # Download BAM files.
    dx download "${input_bam}" --auth "${API_KEY}"


    # Give all users access to docker.sock
    sudo chmod 666 /var/run/docker.sock

    # Load docker image from docker hub

    # docker image pull seglh/toolbox@sha256:edc89eb1e2c90461baa44dfb77d05d0ce8fcac5d064ad31500d325145ca07a5a
    docker image pull seglh/toolbox:latest

    # Execute the dockerised script - args described below:
    # -v Bind the directory in the DNA Nexus instance to the /home folder in the docker app
    # This insures that all the files produced in the docker instance will be saved before the docker instance closes
    # --rm automatically remove the container when it finishes

    docker run -it --rm -v "$(pwd)":/work seglh/toolbox bam2bw ${input_bam}
    
    # Upload results to DNA nexus
    dx-upload-all-outputs
}
